# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
env:
  NAME: testy
  DOCKER_USER: linitsh

dotenv: 
  - .env
tasks:
  default: task -a

  start: bun run index.ts

  docker-build:
  - docker build -t ${NAME} .

  docker-run:
    aliases:
      - r
    cmds:
    - task: docker-build
    - docker run -d --rm --name ${NAME} -p 8080:3000 ${NAME} 
    - echo "http://localhost:8080"

  docker-stop:
    aliases:
      - s
    cmds:
    - docker stop ${NAME}

  push-image:
  - docker login -u ${DOCKER_USER} -p ${TOKEN}
  - docker tag ${NAME} ${DOCKER_USER}/${NAME}
  - docker push

  save:
  - git add .
  - git commit -m {{ default "save" (q .CLI_ARGS) }}
  - git push
