# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
env:
  NAME: testy
  DOCKER_USER: linitsh
  TAG: 0.0.5

dotenv: 
  - .env
tasks:
  default: task -a

  start: bun run index.ts

  build:
  - docker build -f Dockerfile -t ${NAME} .

  run:
    aliases:
      - r
    cmds:
    # - task: docker-stop
    - task: build
    - docker run -d --name ${NAME} -p 8080:3000 ${NAME} 
    - echo "http://localhost:8080"

  stop:
    aliases:
      - s
    cmds:
    - docker stop ${NAME}
    - docker rm ${NAME}

  push:
  - docker login -u ${DOCKER_USER} -p ${TOKEN}
  - docker tag ${NAME} ${DOCKER_USER}/${NAME}:${TAG}
  - docker tag ${NAME} ${DOCKER_USER}/${NAME}:latest
  - docker push ${DOCKER_USER}/${NAME}:${TAG}
  - docker push ${DOCKER_USER}/${NAME}:latest

  connect: 
  - docker exec -it ${NAME} bash

  save:
  - git add .
  - git commit -m {{ default (q .CLI_ARGS) "save"  }}
  - git push


  build-linux:
  - bun build --compile --target=bun-linux-x64 ./index.ts --outfile ./testy
  

  autosave:
  - task: save
  - task: build
  - task: push